Allow configurable prefix for environment secret provider
camunda/connectors pull request #1293
Opened 2023-10-17 08:35 UTC by jonathanlukas

## Description

The Spring Environment Secret Provider has been adjusted to accept a prefix. This allows for easily narrowing down the environment that is accessible through the secret provider.
## Related issues

closes #1290

2023-10-17 09:16 UTC, sbuettner commented on connector-runtime/spring-boot-starter-camunda-connectors/src/test/java/io/camunda/connector/runtime/secret/SpringEnvironmentSecretProviderTest.java
> +      "camunda.connector.secret-provider.environment.prefix=secrets."
```suggestion
      "camunda.connector.secretprovider.discovery.enabled=false",
      "camunda.connector.secretprovider.environment.prefix=secrets."
```

2023-10-17 09:18 UTC, sbuettner commented on connector-runtime/connector-runtime-spring/src/test/java/io/camunda/connector/runtime/env/SpringEnvironmentSecretProviderTest.java
> +    env.setProperty("secrets.MY_TOTAL_SECRET", "beebop");
Idea for better readability: What about using something that looks more like a prefix and not like our own secrets prefix like to not confuse the reader: `my_secret_prefix_` or similar.

2023-10-17 11:51 UTC, sbuettner commented on connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/OutboundConnectorsAutoConfiguration.java
> +  @Value("${camunda.connector.secretprovider.environment.prefix:secrets.}")
Lets not have a default here to be backwards compatible without any suprises.

2023-10-17 14:50 UTC, sbuettner requested changes
Please remove the default prefix.

2023-10-18 07:40 UTC, jonathanlukas commented
@sbuettner I added a PostConstruct method on the SpringEnvironmentSecretProvider that will log WARN if no prefix is configured.

Should we add another log like this before each invocation of `getSecret`?

2023-10-18 08:25 UTC, sbuettner commented
> I added a PostConstruct method on the SpringEnvironmentSecretProvider that will log WARN if no prefix is configured.
I dont think this is necessary as the prefix is completely optional. You could add an info log if you like. Otherwise it could be confusing to users.

2023-10-18 08:27 UTC, jonathanlukas commented
Alright, I can adjust this. As example, I used keycloak that logs WARN if being run in a dev setup (which is considered unsecure), but the threat is much less with connectors... I will adjust the log level ;)

2023-10-18 09:41 UTC, jonathanlukas commented
@sbuettner warn log was replaced by info log now

2023-10-18 10:03 UTC, sbuettner approved these changes

2023-10-18 11:29 UTC, merged