feat(automation anywhere): implement connector
camunda/connectors pull request #1328
Opened 2023-10-25 23:33 UTC by Oleksiivanov

## Description

Implemented code for automation anywhere connector. 

Related : https://github.com/camunda/team-connectors/issues/521

2023-10-26 08:26 UTC, igpetrov commented
It looks to me that it's an HTTP connector. Why would we need to implement it in code then?

2023-10-26 11:30 UTC, sbuettner commented
@igpetrov We want to get rid of the custom authentication method in the http client to simplify it. Hence the need for custom code.

2023-10-26 12:06 UTC, igpetrov commented
> @igpetrov We want to get rid of the custom authentication method in the http client to simplify it. Hence the need for custom code.

@sbuettner @Oleksiivanov oh, I see. that's sad

2023-10-30 11:11 UTC, sbuettner commented on connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/AutomationAnywhereConnector.java
> +public class AutomationAnywhereConnector implements OutboundConnectorFunction {
Can you please use the element template generator?

2023-10-30 11:12 UTC, sbuettner commented on connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/AutomationAnywhereRequest.java
> +public class AutomationAnywhereRequest extends HttpCommonRequest {
Why do you need to inherit here? Cant you just "build" the required http common request in code?

2023-10-30 11:12 UTC, sbuettner requested changes
Please use element template generator and dont inherit model from base.

2023-11-07 10:44 UTC, igpetrov commented on connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/AutomationAnywhereConnector.java
> +  private static final String AUTHENTICATION_HEADER = "X-Authorization";
Consider using `protected` in order to re-use constant in tests.

```suggestion
  protected static final String AUTHENTICATION_HEADER = "X-Authorization";
```

2023-11-07 10:46 UTC, igpetrov commented on connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/model/auth/PasswordBasedAuthenticationStrategy.java
> +    return Map.of("username", username, "password", password, "multipleLogin", multipleLogin);
Here as well

2023-11-07 10:47 UTC, igpetrov requested changes
Minor changes requested.

2023-11-08 12:14 UTC, igpetrov commented on connectors/automation-anywhere/src/main/java/io/camunda/connector/automationanywhere/AutomationAnywhereConnector.java
> +    documentationRef = "https://docs.camunda.io/docs/components/connectors/protocol/rest/",
Doesn't it have it's own doc?

2023-11-08 13:06 UTC, igpetrov approved these changes
LGTM

2023-11-09 07:59 UTC, sbuettner approved these changes
We are missing proper e2e tests. Please add them in another PRs.

2023-11-09 08:09 UTC, merged