feat(easypost): implement easyPost connector
camunda/connectors pull request #385
Opened 2023-03-21 20:03 UTC by Oleksiivanov

## Description

Allow create a shipment, buy a shipment, and get a status tracker.

https://user-images.githubusercontent.com/108869886/226897091-d6a06843-f971-4232-a40a-eb95ea9c589b.mov

## Related issues
 https://github.com/camunda/connectors-bundle/issues/384
https://github.com/camunda/team-connectors/issues/363

2023-03-27 14:56 UTC, bastiankoerber requested changes
just minor adjustments

2023-03-27 14:56 UTC, bastiankoerber commented on connectors/easy-post/element-templates/easy-post-connector.json
> +  "description": "Orchestrate your Easy Post shipment with Camunda",
orchestrate doesn't fit in this context.
Maybe sth like this: It allows you to create addresses, parcels, and shipments, as well as purchase and verify shipments.

2023-03-27 14:56 UTC, bastiankoerber commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "ity the address is located in",
C in City is missing

2023-03-27 14:56 UTC, bastiankoerber commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "ZIP or postal code the address is located in",
make it easier: The ZIP or postal code where the address is located.

2023-03-27 14:56 UTC, bastiankoerber commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "<a href=\"https://www.iso.org/iso-3166-country-codes.html\" target=\"_blank\">ISO 3166</a> country code for the country the address is located in",
same here: The country code of the address location

2023-03-27 14:56 UTC, bastiankoerber commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "ID of the salready created addres",
typo and please replace with: The ID of the address that has already been created.

2023-03-28 16:57 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +  "description": "It allows you to create addresses, parcels, and shipments, as well as purchase and verify shipments",
```suggestion
  "description": "Allows you to create addresses, parcels, and shipments, as well as purchase and verify shipments",
```

2023-03-28 16:59 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "authentication type",
Actually, remove all non-required fields, since this is hidden.

2023-03-28 17:00 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "this field will replace to empty string. easypost API use only username field for put API Key",
Either remove or

```suggestion
      "description": "This field will replace to empty string. EasyPost API use only username field for put API Key",
```

2023-03-28 17:01 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "label": "Street1",
```suggestion
      "label": "Address line 1",
```

2023-03-28 17:02 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "label": "Street2",
```suggestion
      "label": "Address line 2",
```

2023-03-28 17:03 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "label": "ZIP",
```suggestion
      "label": "ZIP or postal code",
```

2023-03-28 17:04 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +        "name": "body.address.federal_tax_id"
```suggestion
        "name": "body.address.federalTaxId"
```

2023-03-28 17:05 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +        "name": "body.address.state_tax_id"
```suggestion
        "name": "body.address.stateTaxId"
```

2023-03-28 17:06 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +        "name": "body.parcel.predefined_package"
```suggestion
        "name": "body.parcel.predefinedPackage"
```

2023-03-28 17:08 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "description": "create address url",
Either remove or normalize

2023-03-29 11:27 UTC, igpetrov commented on connectors/easy-post/element-templates/easy-post-connector.json
> +      "label": "Shipment id",
```suggestion
      "label": "Shipment ID",
```

2023-03-29 11:27 UTC, igpetrov approved these changes

2023-03-29 11:50 UTC, merged