feat(googleMapsPlatform): create connector
camunda/connectors pull request #391
Opened 2023-03-22 21:07 UTC by Oleksiivanov

## Description

Google Maps Platform Connector.
Allows : 
- validate address
- format address
- get place id for the address
- get postal address from (postal code, region code, etc)
- calculate the distance and duration between two addresses 

https://user-images.githubusercontent.com/108869886/227038028-6038938f-9488-4c2c-8979-207b5db16a9e.mov

## Related issues
https://github.com/camunda/team-connectors/issues/363

2023-03-27 14:47 UTC, bastiankoerber requested changes
some wording and one wrong link. Rest looks good :-)

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +  "description": "Orchestrate your Google Maps Platform operations with Camunda. You can validate and format address, get postal address, calculate distance, etc.",
orhcestrate doesn't fit in this contect, add this as description:
The Google Maps connector validates addresses, retrieves postal addresses and calculates distances.

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +          "name": "Directions",
what do you mean with directtions?

Do you mean distance? then call it: Calculate Distance

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +          "name": "Validate an address",
replace with Validate Adress

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "Google Maps Platform API key. Details in the <a href='https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/microsoft-teams/'>connector documentation</a>"
replace the documentation link

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "Complete address. Detailes in a <a href='https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/google-maps-platform/'> connector documantation</a>",
typo in details

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "The place ID value to which you wish to calculate directions",
replace with: The place ID value that you want to use as the destination for calculating distance.

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "The place ID value from which you wish to calculate directions.",
replace with: The place ID value that you want to use as the starting point for calculating distance.

2023-03-27 14:47 UTC, bastiankoerber commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "For the calculation of distances and directions, you may specify the transportation mode to use",
replace with: You can specify the transportation mode to use when calculating distances and directions.

2023-03-28 17:43 UTC, igpetrov commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "description": "post method",
Normalize or remove (applicable to all similar occurances)

2023-03-28 17:43 UTC, igpetrov commented on connectors/google-maps-platform/element-templates/google-maps-platform-connector.json
> +      "label": "API Key",
```suggestion
      "label": "API key",
```

2023-03-28 17:44 UTC, igpetrov requested changes
LGTM. Minor changes requested.

2023-03-29 11:26 UTC, igpetrov approved these changes

2023-03-29 11:26 UTC, igpetrov commented
Don't forget to squash the PR into 1 commit

2023-03-29 11:44 UTC, merged