Implement Twilio outbound connector
camunda/connectors pull request #474
Opened 2023-04-17 19:09 UTC by Oleksiivanov

## Description

Implement Twilio outbound connector

## Related issues

https://github.com/camunda/product-hub/issues/1138

closes #
https://github.com/camunda/connectors-bundle/issues/402

2023-04-20 09:02 UTC, igpetrov requested changes
LGTM, some changes requested.

2023-04-20 09:02 UTC, igpetrov commented on connectors/twilio/element-templates/twilio-connector.json
> +      "label": "Auth token",
1. Let's not use jargon `Auth` => `Authentication` etc.
2. Let's maintain the same style of labels everywhere. If you write here `Authentication token` then the next one has to be `Message text` and not `...Text` with capitalized first letter.

```suggestion
      "label": "Authentication token",
```

2023-04-21 10:20 UTC, bastiankoerber reviewed
looks good, just some minor changes

2023-04-21 10:20 UTC, bastiankoerber commented on connectors/twilio/element-templates/twilio-connector.json
> +      "description": "Your Twilio account SID. For more information, see <a href=\"https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/twilio/\" target=\"_blank\">Camunda doc
keep it consistent. Remove for more information and just say: see <link>

2023-04-21 10:20 UTC, bastiankoerber commented on connectors/twilio/element-templates/twilio-connector.json
> +      "description": "Your Twilio auth token. For more information, see <a href=\"https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/twilio/\" target=\"_blank\">Camunda docu
remove for more information

2023-04-21 10:20 UTC, bastiankoerber commented on connectors/twilio/element-templates/twilio-connector.json
> +      "description": "The message SID to retrieve information about",
replace with: Obtain information regarding the message with SID

2023-04-21 10:20 UTC, bastiankoerber commented on connectors/twilio/element-templates/twilio-connector.json
> +      "description": "The text of the message to be sent",
replace with: The content of the message that will be sent

2023-04-21 10:20 UTC, bastiankoerber commented on connectors/twilio/element-templates/twilio-connector.json
> +      "description": "The Twilio phone number to send the message from",
replace with: The originating Twilio phone number used for sending the message

2023-04-21 12:21 UTC, igpetrov approved these changes
LGTM, thank you.

2023-04-23 15:48 UTC, merged