feat(aws): add inbound eventbridge connector template
camunda/connectors pull request #905
Opened 2023-07-18 03:39 UTC by Oleksiivanov

## Description

Added inbound aws eventbridge connector template

## Related issues
tested with next fix : https://github.com/camunda/connectors-bundle/pull/913

depend on https://github.com/camunda/connectors-bundle/pull/920

<img width="611" alt="Screenshot 2023-07-20 at 20 52 11" src="https://github.com/camunda/connectors-bundle/assets/108869886/03a33bea-c6ca-4884-a96f-0196ff15edd9">
<img width="361" alt="Screenshot 2023-07-20 at 20 52 24" src="https://github.com/camunda/connectors-bundle/assets/108869886/b6510463-132e-4a88-ae91-30b16b07ad01">
<img width="359" alt="Screenshot 2023-07-20 at 20 52 32" src="https://github.com/camunda/connectors-bundle/assets/108869886/87707198-d2c4-464a-a0cf-4c1543e4f185">
<img width="355" alt="Screenshot 2023-07-20 at 20 52 38" src="https://github.com/camunda/connectors-bundle/assets/108869886/aae57853-52c1-43fd-950d-4a51de3da583">
<img width="346" alt="Screenshot 2023-07-20 at 20 52 47" src="https://github.com/camunda/connectors-bundle/assets/108869886/705e8f8a-e9b1-4a03-9f53-9b742aebeae1">

2023-07-21 12:25 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +      "description": "Choose the authorization type.",
```suggestion
      "description": "Choose the authorization type",
```

2023-07-21 12:25 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +      "label": "JWK url",
```suggestion
      "label": "JWK URL",
```

2023-07-21 12:25 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +      "description": "Well-known url of JWKs",
```suggestion
      "description": "Well-known URL of JWKs",
```

2023-07-21 12:25 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +      "label": "API Key locator",
```suggestion
      "label": "API key locator",
```

2023-07-21 12:26 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-start-event.json
Same proposals as above

2023-07-21 12:26 UTC, igpetrov requested changes
LGTM, minor suggestions

2023-07-21 12:42 UTC, igpetrov commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-start-event.json
the `key` in label should also start from small `k`.

2023-07-21 12:48 UTC, igpetrov approved these changes

2023-07-26 07:46 UTC, sbuettner commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +      "label": "Webhook configuration"
Lets call it `API destination` as this is the term AWS uses as well

2023-07-26 13:42 UTC, sbuettner requested changes

2023-07-26 13:42 UTC, sbuettner commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-intermediate.json
> +  "description": "Send events to AWS EventBridge",
"Receive events from AWS EventBridge"

2023-07-26 13:42 UTC, sbuettner commented on connectors/aws/aws-eventbridge/element-templates/aws-eventbridge-connector-start-event.json
> +  "description": "Send events to AWS EventBridge",
see above

2023-07-26 13:48 UTC, sbuettner approved these changes

2023-07-26 13:52 UTC, merged